spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-name: Kakao
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
          naver:
            client-id: ${NAVER_CLIENT_ID:EqH2aINMof0s9WzYpbo1}
            client-secret: ${NAVER_CLIENT_SECRET:eZmQZfjbZ3}
            client-name: Naver
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, nickname, gender, age, birthday, profile_image, birthyear, mobile

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  config:
    import:
      - classpath:/jwt.yml
server:
  servlet:
    context-path: /api
    session:
      tracking-modes: cookie